

CREATE UNIQUE INDEX "AFILIACION"."AFL_CAMPANIA_PK" ON "AFILIACION"."AFL_CAMPANIA" ("ID_CAMPANIA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE( INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_AFILIACION"  ;
  
  ALTER INDEX "AFILIACION"."AFL_CAMPANIA_PK"  UNUSABLE
  
  
  
  alter table rp_estad_universo_mrc modify ACTIVOS_LIQUIDADOS NUMBER(18,3) null;