--- consulta para listar los aplicativos que tiene un usuario. 
falta filtrar el cargo

SELECT 
    c.nombre AS Cargo,
    a.nombre AS Aplicativo
FROM 
    Permisos p
JOIN 
    Aplicativos a ON p.aplicativo_id = a.id
JOIN 
    Cargos c ON p.cargo_id = c.id
WHERE 
    p.permiso = 'X';




---- tablas

####### Aplicativos ############
CREATE TABLE APLICATIVOS (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(255) NOT NULL
);

########### Cargos ###################
CREATE TABLE CARGOS (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(255) NOT NULL
);


########### Permisos ###################
CREATE TABLE PERMISOS (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    aplicativo_id NUMBER NOT NULL,
    cargo_id NUMBER NOT NULL,
    permiso CHAR(1) CHECK (permiso IN ('X', ' ')),
    FOREIGN KEY (aplicativo_id) REFERENCES Aplicativos(id),
    FOREIGN KEY (cargo_id) REFERENCES Cargos(id)
);

#### insert ################


-- Insertar aplicativos
INSERT INTO Aplicativos (nombre) VALUES ('Acceso modificar página web CCC');
INSERT INTO Aplicativos (nombre) VALUES ('Acrobat Unir PDF');
INSERT INTO Aplicativos (nombre) VALUES ('Actualización de Mercantil/ESAL');
INSERT INTO Aplicativos (nombre) VALUES ('Administrador de riesgos');
INSERT INTO Aplicativos (nombre) VALUES ('Adobe Creative Cloud');
INSERT INTO Aplicativos (nombre) VALUES ('AdSecurity');
INSERT INTO Aplicativos (nombre) VALUES ('Agente de impresión de certificados y recibos');
INSERT INTO Aplicativos (nombre) VALUES ('Antivirus');
INSERT INTO Aplicativos (nombre) VALUES ('Aplicación para registro de actividades del personal de otras areas');
INSERT INTO Aplicativos (nombre) VALUES ('Aplicación para registro de actividades del personal de Tecnología');
INSERT INTO Aplicativos (nombre) VALUES ('Aplicación web para liquidar y pagar los servicios del Centro de Conciliación');
INSERT INTO Aplicativos (nombre) VALUES ('Archivar PDFs de Renovación en Docunet');
INSERT INTO Aplicativos (nombre) VALUES ('Autoliquidación');
INSERT INTO Aplicativos (nombre) VALUES ('Avaya');
INSERT INTO Aplicativos (nombre) VALUES ('Avianca preferencia corporativa');
INSERT INTO Aplicativos (nombre) VALUES ('Banco audio visual CCC en smugmug.com');
INSERT INTO Aplicativos (nombre) VALUES ('Biable');
INSERT INTO Aplicativos (nombre) VALUES ('Bizagy');
INSERT INTO Aplicativos (nombre) VALUES ('Cajas web');
INSERT INTO Aplicativos (nombre) VALUES ('Campus virtual, diplomados virtuales');
INSERT INTO Aplicativos (nombre) VALUES ('Cardpresso (impresión de credenciales)');
INSERT INTO Aplicativos (nombre) VALUES ('Centro de crecimiento empresarial');
INSERT INTO Aplicativos (nombre) VALUES ('Certificado de Estado de Cédula de Ciudadanía');
INSERT INTO Aplicativos (nombre) VALUES ('Certificado electrónico');
INSERT INTO Aplicativos (nombre) VALUES ('CGUNO');
INSERT INTO Aplicativos (nombre) VALUES ('Claro');
INSERT INTO Aplicativos (nombre) VALUES ('Clasificador');
INSERT INTO Aplicativos (nombre) VALUES ('Conozca a su cliente');
INSERT INTO Aplicativos (nombre) VALUES ('Constitución de SAS');
INSERT INTO Aplicativos (nombre) VALUES ('Consulta códigos CIIU');
INSERT INTO Aplicativos (nombre) VALUES ('Consulta de certificados RUES - Confecamaras');
INSERT INTO Aplicativos (nombre) VALUES ('Consulta de homonimia');
INSERT INTO Aplicativos (nombre) VALUES ('Consulta de información de usuarios externos');
INSERT INTO Aplicativos (nombre) VALUES ('Consulta de PDF de RUES anteriores al año 2012');
INSERT INTO Aplicativos (nombre) VALUES ('Consulta de PDF de RUES despues del año 2012');
INSERT INTO Aplicativos (nombre) VALUES ('Consulta del estado del RUT');
INSERT INTO Aplicativos (nombre) VALUES ('Consulta del Estado Trámite');
INSERT INTO Aplicativos (nombre) VALUES ('Consulta expedientes (entidades estatales)');
INSERT INTO Aplicativos (nombre) VALUES ('Consulta expedientes internas');
INSERT INTO Aplicativos (nombre) VALUES ('Conversion de imágenes a PDF /TIF');
INSERT INTO Aplicativos (nombre) VALUES ('Correo electrónico');
INSERT INTO Aplicativos (nombre) VALUES ('Creacion del RUT');
INSERT INTO Aplicativos (nombre) VALUES ('Dali Enterprise');
INSERT INTO Aplicativos (nombre) VALUES ('Devolucion de documentos');
INSERT INTO Aplicativos (nombre) VALUES ('Docunet Registro Web');
INSERT INTO Aplicativos (nombre) VALUES ('Easy Corporate');
INSERT INTO Aplicativos (nombre) VALUES ('Elecciones para Junta Directiva');
INSERT INTO Aplicativos (nombre) VALUES ('Escaneo de archivos');
INSERT INTO Aplicativos (nombre) VALUES ('Evento 2017');
INSERT INTO Aplicativos (nombre) VALUES ('Facturador Web - Cuota de Afiliación');
INSERT INTO Aplicativos (nombre) VALUES ('Firmar de imágenes');
INSERT INTO Aplicativos (nombre) VALUES ('Formulario de inscripción al evento Martes del Aliado');
INSERT INTO Aplicativos (nombre) VALUES ('Formulario de inscripción Bion');
INSERT INTO Aplicativos (nombre) VALUES ('Formulario de inscripción Ley 1429');
INSERT INTO Aplicativos (nombre) VALUES ('Formulario de registro y pago de los eventos');
INSERT INTO Aplicativos (nombre) VALUES ('Formulario web de inscripción de Exponegocios');
INSERT INTO Aplicativos (nombre) VALUES ('Garantias mobiliarias');
INSERT INTO Aplicativos (nombre) VALUES ('Generacion certificado experian');
INSERT INTO Aplicativos (nombre) VALUES ('Gestión de los activos fijos de la cámara: Equipos, servidores, dispositivos, etc');
INSERT INTO Aplicativos (nombre) VALUES ('Gestor documental administrativo');
INSERT INTO Aplicativos (nombre) VALUES ('Gestor documental Cliente Servidor');
INSERT INTO Aplicativos (nombre) VALUES ('Google Earth Pro');
INSERT INTO Aplicativos (nombre) VALUES ('Ilustrator');
INSERT INTO Aplicativos (nombre) VALUES ('Información de sistema gestión de calidad');
INSERT INTO Aplicativos (nombre) VALUES ('Inscripcion de actos y documentos');
INSERT INTO Aplicativos (nombre) VALUES ('Inspektor Datalaf');
INSERT INTO Aplicativos (nombre) VALUES ('Instructivo Registros Púbicos');
INSERT INTO Aplicativos (nombre) VALUES ('Inteligencia de Negocios');
INSERT INTO Aplicativos (nombre) VALUES ('Intranet de CCC');
INSERT INTO Aplicativos (nombre) VALUES ('Key');
INSERT INTO Aplicativos (nombre) VALUES ('Kujis');
INSERT INTO Aplicativos (nombre) VALUES ('LASERFICHE');
INSERT INTO Aplicativos (nombre) VALUES ('Latam');
INSERT INTO Aplicativos (nombre) VALUES ('Legis Tienen un usuario para todos (ccya@ccc.org,co');
INSERT INTO Aplicativos (nombre) VALUES ('Libros Electrónicos');
INSERT INTO Aplicativos (nombre) VALUES ('Martillo electronico - Confecamaras');
INSERT INTO Aplicativos (nombre) VALUES ('Matricula de Mercantil/ESAL');
INSERT INTO Aplicativos (nombre) VALUES ('Monitoreo de red');
INSERT INTO Aplicativos (nombre) VALUES ('Nómina WEB');
INSERT INTO Aplicativos (nombre) VALUES ('ontaPyme');
INSERT INTO Aplicativos (nombre) VALUES ('Página Cabify');
INSERT INTO Aplicativos (nombre) VALUES ('página del DIAN');
INSERT INTO Aplicativos (nombre) VALUES ('página Pago seguridad social (aporte en linea)');
INSERT INTO Aplicativos (nombre) VALUES ('Pagina web de solicitud de papeleria');
INSERT INTO Aplicativos (nombre) VALUES ('páginas de ARL');
INSERT INTO Aplicativos (nombre) VALUES ('páginas de bancos');
INSERT INTO Aplicativos (nombre) VALUES ('páginas de compensacion');
INSERT INTO Aplicativos (nombre) VALUES ('páginas de hoteles');
INSERT INTO Aplicativos (nombre) VALUES ('páginas Fondo de pensiones (Historia laboral)');
INSERT INTO Aplicativos (nombre) VALUES ('páginas Universidades');
INSERT INTO Aplicativos (nombre) VALUES ('Panturismo');
INSERT INTO Aplicativos (nombre) VALUES ('Portal de consultas');
INSERT INTO Aplicativos (nombre) VALUES ('Portal EDOX Colombia SAS');
INSERT INTO Aplicativos (nombre) VALUES ('Pow Toon Internet');
INSERT INTO Aplicativos (nombre) VALUES ('Proponentes inscripción, actualizacion');
INSERT INTO Aplicativos (nombre) VALUES ('PSEAG');
INSERT INTO Aplicativos (nombre) VALUES ('Quemador de discos');
INSERT INTO Aplicativos (nombre) VALUES ('Recuperar archivos que no llegan a SIRP');
INSERT INTO Aplicativos (nombre) VALUES ('Registro de Nombramientos');
INSERT INTO Aplicativos (nombre) VALUES ('Registro Nacional de Turismo');
INSERT INTO Aplicativos (nombre) VALUES ('Registro Único Empresarial y Social RUES');
INSERT INTO Aplicativos (nombre) VALUES ('Registro Único nal operadores de libranza');
INSERT INTO Aplicativos (nombre) VALUES ('Renovación de Mercantil/ESAL Local');
INSERT INTO Aplicativos (nombre) VALUES ('Renovación de Mercantil/ESAL Nacional');
INSERT INTO Aplicativos (nombre) VALUES ('Reserva de salas');
INSERT INTO Aplicativos (nombre) VALUES ('Sanción a Contadores');
INSERT INTO Aplicativos (nombre) VALUES ('ShutterStock');
INSERT INTO Aplicativos (nombre) VALUES ('SICAAC Sistema de informacion de la conciliacion el arbitraje y la amigable composición');
INSERT INTO Aplicativos (nombre) VALUES ('SIRP consulta');
INSERT INTO Aplicativos (nombre) VALUES ('SIRP PQRS');
INSERT INTO Aplicativos (nombre) VALUES ('Sistema de actualización automático de Tarifas de servicios públicos');
INSERT INTO Aplicativos (nombre) VALUES ('Sistema de administracion de afiliados');
INSERT INTO Aplicativos (nombre) VALUES ('Sistema de administración de usuarios - Interno');
INSERT INTO Aplicativos (nombre) VALUES ('Sistema de auditoria de aplicaciones');
INSERT INTO Aplicativos (nombre) VALUES ('Sistema de auditoria de aplicaciones Audisolutions');
INSERT INTO Aplicativos (nombre) VALUES ('Sistema de misiones');
INSERT INTO Aplicativos (nombre) VALUES ('Sistema de Turnos, configuración de usuarios');
INSERT INTO Aplicativos (nombre) VALUES ('Sistema Financiero y Contable');
INSERT INTO Aplicativos (nombre) VALUES ('Sistema integrado de registros publicos cajas');
INSERT INTO Aplicativos (nombre) VALUES ('Sistema integrado de registros publicos certificados');
INSERT INTO Aplicativos (nombre) VALUES ('Sistema integrado de registros publicos registro');
INSERT INTO Aplicativos (nombre) VALUES ('Sistema nacional del registro de emplazados');
INSERT INTO Aplicativos (nombre) VALUES ('Sistema para la gestión de presupuesto de la entidad');
INSERT INTO Aplicativos (nombre) VALUES ('Sistema Registro Nacional de Medidas Correctivas RNMC (Policia)');
INSERT INTO Aplicativos (nombre) VALUES ('Sistemas contratos ORION');
INSERT INTO Aplicativos (nombre) VALUES ('Sistemas de apoyo a la mesa de servicios MAS- ARANDA');
INSERT INTO Aplicativos (nombre) VALUES ('Sistemas de estadisticas de SIRP');
INSERT INTO Aplicativos (nombre) VALUES ('Site administratión');
INSERT INTO Aplicativos (nombre) VALUES ('Software de Control de acceso (Externo)');
INSERT INTO Aplicativos (nombre) VALUES ('Software de control de visitantes (Externo)');
INSERT INTO Aplicativos (nombre) VALUES ('Software de visualización de DVRs (Externo)');
INSERT INTO Aplicativos (nombre) VALUES ('Stata');
INSERT INTO Aplicativos (nombre) VALUES ('Tableau');
INSERT INTO Aplicativos (nombre) VALUES ('Trello');
INSERT INTO Aplicativos (nombre) VALUES ('Trusteer Rapport -pago bancos');
INSERT INTO Aplicativos (nombre) VALUES ('Validación cédulas de extranjería');
INSERT INTO Aplicativos (nombre) VALUES ('Validador de identidad');
INSERT INTO Aplicativos (nombre) VALUES ('Venta de información de comerciantes por tipo de actividad y otros criterios');
INSERT INTO Aplicativos (nombre) VALUES ('Verificar la imagen que llega de RUES');
INSERT INTO Aplicativos (nombre) VALUES ('VPN');
INSERT INTO Aplicativos (nombre) VALUES ('Wetransfer');
INSERT INTO Aplicativos (nombre) VALUES ('Wix Internet');
INSERT INTO Aplicativos (nombre) VALUES ('Zoom');

select * from APLICATIVOS ;




-- Insertar cargos
INSERT INTO Cargos (nombre) VALUES ('Registros Publicos y Redes Empresariales');
INSERT INTO Cargos (nombre) VALUES ('Director de Registros Públicos');
INSERT INTO Cargos (nombre) VALUES ('Asistente de Registros Públicos');

select * from CARGOS ;

-- Agrega más cargos según sea necesario

-- Insertar permisos

-- Insertar permisos para el cargo "Registros Publicos y Redes Empresariales"
INSERT INTO Permisos (aplicativo_id, cargo_id, permiso) VALUES (1, 1, 'X');
INSERT INTO Permisos (aplicativo_id, cargo_id, permiso) VALUES (2, 1, 'X');
INSERT INTO Permisos (aplicativo_id, cargo_id, permiso) VALUES (3, 1, 'X');
INSERT INTO Permisos (aplicativo_id, cargo_id, permiso) VALUES (4, 1, 'X');
INSERT INTO Permisos (aplicativo_id, cargo_id, permiso) VALUES (5, 1, 'X');
INSERT INTO Permisos (aplicativo_id, cargo_id, permiso) VALUES (6, 1, 'X');
INSERT INTO Permisos (aplicativo_id, cargo_id, permiso) VALUES (7, 1, 'X');
INSERT INTO Permisos (aplicativo_id, cargo_id, permiso) VALUES (8, 1, 'X');
INSERT INTO Permisos (aplicativo_id, cargo_id, permiso) VALUES (9, 1, 'X');
INSERT INTO Permisos (aplicativo_id, cargo_id, permiso) VALUES (10, 1, 'X');
INSERT INTO Permisos (aplicativo_id, cargo_id, permiso) VALUES (11, 1, 'X');
INSERT INTO Permisos (aplicativo_id, cargo_id, permiso) VALUES (12, 1, 'X');
INSERT INTO Permisos (aplicativo_id, cargo_id, permiso) VALUES (13, 1, 'X');
INSERT INTO Permisos (aplicativo_id, cargo_id, permiso) VALUES (14, 1, 'X');
INSERT INTO Permisos (aplicativo_id, cargo_id, permiso) VALUES (15, 1, 'X');
INSERT INTO Permisos (aplicativo_id, cargo_id, permiso) VALUES (16, 1, 'X');
INSERT INTO Permisos (aplicativo_id, cargo_id, permiso) VALUES (17, 1, 'X');
INSERT INTO Permisos (aplicativo_id, cargo_id, permiso) VALUES (18, 1, 'X');
INSERT INTO Permisos (aplicativo_id, cargo_id, permiso) VALUES (19, 1, 'X');
INSERT INTO Permisos (aplicativo_id, cargo_id, permiso) VALUES (20, 1, 'X');
INSERT INTO Permisos (aplicativo_id, cargo_id, permiso) VALUES (21, 1, 'X');
INSERT INTO Permisos (aplicativo_id, cargo_id, permiso) VALUES (22, 1, 'X');
INSERT INTO Permisos (aplicativo_id, cargo_id, permiso) VALUES (23, 1, 'X');
INSERT INTO Permisos (aplicativo_id, cargo_id, permiso) VALUES (24, 1, 'X');
INSERT INTO Permisos (aplicativo_id, cargo_id, permiso) VALUES (25, 1, 'X');
INSERT INTO Permisos (aplicativo_id, cargo_id, permiso) VALUES (26, 1, 'X');
INSERT INTO Permisos (aplicativo_id, cargo_id, permiso) VALUES (27, 1, '');
INSERT INTO Permisos (aplicativo_id, cargo_id, permiso) VALUES (28, 1, 'X');
INSERT INTO Permisos (aplicativo_id, cargo_id, permiso) VALUES (29, 1, 'X');
INSERT INTO Permisos (aplicativo_id, cargo_id, permiso) VALUES (30, 1, 'X');
INSERT INTO Permisos (aplicativo_id, cargo_id, permiso) VALUES (31, 1, 'X');
INSERT INTO Permisos (aplicativo_id, cargo_id, permiso) VALUES (32, 1, 'X');
INSERT INTO Permisos (aplicativo_id, cargo_id, permiso) VALUES (33, 1, '');
INSERT INTO Permisos (aplicativo_id, cargo_id, permiso) VALUES (34, 1, 'X');
INSERT INTO Permisos (aplicativo_id, cargo_id, permiso) VALUES (35, 1, '');
INSERT INTO Permisos (aplicativo_id, cargo_id, permiso) VALUES (36, 1, 'X');
INSERT INTO Permisos (aplicativo_id, cargo_id, permiso) VALUES (37, 1, 'X');
INSERT INTO Permisos (aplicativo_id, cargo_id, permiso) VALUES (38, 1, 'X');
INSERT INTO Permisos (aplicativo_id, cargo_id, permiso) VALUES (39, 1, 'X');
INSERT INTO Permisos (aplicativo_id, cargo_id, permiso) VALUES (40, 1, 'X');
INSERT INTO Permisos (aplicativo_id, cargo_id, permiso) VALUES (41, 1, 'X');
INSERT INTO Permisos (aplicativo_id, cargo_id, permiso) VALUES (42, 1, 'X');
INSERT INTO Permisos (aplicativo_id, cargo_id, permiso) VALUES (43, 1, '');
INSERT INTO Permisos (aplicativo_id, cargo_id, permiso) VALUES (44, 1, 'X');
INSERT INTO Permisos (aplicativo_id, cargo_id, permiso) VALUES (45, 1, 'X');
INSERT INTO Permisos (aplicativo_id, cargo_id, permiso) VALUES (46, 1, 'X');
INSERT INTO Permisos (aplicativo_id, cargo_id, permiso) VALUES (47, 1, 'X');
INSERT INTO Permisos (aplicativo_id, cargo_id, permiso) VALUES (48, 1, '');
INSERT INTO Permisos (aplicativo_id, cargo_id, permiso) VALUES (49, 1, 'X');
INSERT INTO Permisos (aplicativo_id, cargo_id, permiso) VALUES (50, 1, '');
INSERT INTO Permisos (aplicativo_id, cargo_id, permiso) VALUES (51, 1, 'X');
INSERT INTO Permisos (aplicativo_id, cargo_id, permiso) VALUES (52, 1, 'X');
INSERT INTO Permisos (aplicativo_id, cargo_id, permiso) VALUES (53, 1, 'X');
INSERT INTO Permisos (aplicativo_id, cargo_id, permiso) VALUES (54, 1, '');
INSERT INTO Permisos (aplicativo_id, cargo_id, permiso) VALUES (55, 1, 'X');
INSERT INTO Permisos (aplicativo_id, cargo_id, permiso) VALUES (56, 1, 'X');
INSERT INTO Permisos (aplicativo_id, cargo_id, permiso) VALUES (57, 1, 'X');
INSERT INTO Permisos (aplicativo_id, cargo_id, permiso) VALUES (58, 1, 'X');
INSERT INTO Permisos (aplicativo_id, cargo_id, permiso) VALUES (59, 1, 'X');
INSERT INTO Permisos (aplicativo_id, cargo_id, permiso) VALUES (60, 1, 'X');
INSERT INTO Permisos (aplicativo_id, cargo_id, permiso) VALUES (61, 1, 'X');
INSERT INTO Permisos (aplicativo_id, cargo_id, permiso) VALUES (62, 1, 'X');
INSERT INTO Permisos (aplicativo_id, cargo_id, permiso) VALUES (63, 1, '');
INSERT INTO Permisos (aplicativo_id, cargo_id, permiso) VALUES (64, 1, '');
INSERT INTO Permisos (aplicativo_id, cargo_id, permiso) VALUES (65, 1, '');
INSERT INTO Permisos (aplicativo_id, cargo_id, permiso) VALUES (66, 1, '');
INSERT INTO Permisos (aplicativo_id, cargo_id, permiso) VALUES (67, 1, 'X');
INSERT INTO Permisos (aplicativo_id, cargo_id, permiso) VALUES (68, 1, '');
INSERT INTO Permisos (aplicativo_id, cargo_id, permiso) VALUES (69, 1, 'X');
INSERT INTO Permisos (aplicativo_id, cargo_id, permiso) VALUES (70, 1, 'X');
INSERT INTO Permisos (aplicativo_id, cargo_id, permiso) VALUES (71, 1, 'X');
INSERT INTO Permisos (aplicativo_id, cargo_id, permiso) VALUES (72, 1, 'X');
INSERT INTO Permisos (aplicativo_id, cargo_id, permiso) VALUES (73, 1, '');
INSERT INTO Permisos (aplicativo_id, cargo_id, permiso) VALUES (74, 1, '');
INSERT INTO Permisos (aplicativo_id, cargo_id, permiso) VALUES (75, 1, 'X');
INSERT INTO Permisos (aplicativo_id, cargo_id, permiso) VALUES (76, 1, 'X');
INSERT INTO Permisos (aplicativo_id, cargo_id, permiso) VALUES (77, 1, 'X');
INSERT INTO Permisos (aplicativo_id, cargo_id, permiso) VALUES (78, 1, 'X');
INSERT INTO Permisos (aplicativo_id, cargo_id, permiso) VALUES (79, 1, 'X');
INSERT INTO Permisos (aplicativo_id, cargo_id, permiso) VALUES (80, 1, 'X');
INSERT INTO Permisos (aplicativo_id, cargo_id, permiso) VALUES (81, 1, 'X');
INSERT INTO Permisos (aplicativo_id, cargo_id, permiso) VALUES (82, 1, '');
INSERT INTO Permisos (aplicativo_id, cargo_id, permiso) VALUES (83, 1, 'X');
INSERT INTO Permisos (aplicativo_id, cargo_id, permiso) VALUES (84, 1, 'X');
INSERT INTO Permisos (aplicativo_id, cargo_id, permiso) VALUES (85, 1, 'X');
INSERT INTO Permisos (aplicativo_id, cargo_id, permiso) VALUES (86, 1, 'X');
INSERT INTO Permisos (aplicativo_id, cargo_id, permiso) VALUES (87, 1, 'X');
INSERT INTO Permisos (aplicativo_id, cargo_id, permiso) VALUES (88, 1, 'X');
INSERT INTO Permisos (aplicativo_id, cargo_id, permiso) VALUES (89, 1, 'X');
INSERT INTO Permisos (aplicativo_id, cargo_id, permiso) VALUES (90, 1, 'X');
INSERT INTO Permisos (aplicativo_id, cargo_id, permiso) VALUES (91, 1, 'X');
INSERT INTO Permisos (aplicativo_id, cargo_id, permiso) VALUES (92, 1, 'X');
INSERT INTO Permisos (aplicativo_id, cargo_id, permiso) VALUES (93, 1, 'X');
INSERT INTO Permisos (aplicativo_id, cargo_id, permiso) VALUES (94, 1, 'X');
INSERT INTO Permisos (aplicativo_id, cargo_id, permiso) VALUES (95, 1, 'X');
INSERT INTO Permisos (aplicativo_id, cargo_id, permiso) VALUES (96, 1, 'X');
INSERT INTO Permisos (aplicativo_id, cargo_id, permiso) VALUES (97, 1, 'X');
INSERT INTO Permisos (aplicativo_id, cargo_id, permiso) VALUES (98, 1, 'X');
INSERT INTO Permisos (aplicativo_id, cargo_id, permiso) VALUES (99, 1, '');
INSERT INTO Permisos (aplicativo_id, cargo_id, permiso) VALUES (100, 1, 'X');
INSERT INTO Permisos (aplicativo_id, cargo_id, permiso) VALUES (101, 1, 'X');
INSERT INTO Permisos (aplicativo_id, cargo_id, permiso) VALUES (102, 1, '');
INSERT INTO Permisos (aplicativo_id, cargo_id, permiso) VALUES (103, 1, '');
INSERT INTO Permisos (aplicativo_id, cargo_id, permiso) VALUES (104, 1, '');
INSERT INTO Permisos (aplicativo_id, cargo_id, permiso) VALUES (105, 1, '');
INSERT INTO Permisos (aplicativo_id, cargo_id, permiso) VALUES (106, 1, '');
INSERT INTO Permisos (aplicativo_id, cargo_id, permiso) VALUES (107, 1, '');
INSERT INTO Permisos (aplicativo_id, cargo_id, permiso) VALUES (108, 1, '');
INSERT INTO Permisos (aplicativo_id, cargo_id, permiso) VALUES (109, 1, '');
INSERT INTO Permisos (aplicativo_id, cargo_id, permiso) VALUES (110, 1, 'X');
INSERT INTO Permisos (aplicativo_id, cargo_id, permiso) VALUES (111, 1, 'X');
INSERT INTO Permisos (aplicativo_id, cargo_id, permiso) VALUES (112, 1, '');
INSERT INTO Permisos (aplicativo_id, cargo_id, permiso) VALUES (113, 1, '');
INSERT INTO Permisos (aplicativo_id, cargo_id, permiso) VALUES (114, 1, '');
INSERT INTO Permisos (aplicativo_id, cargo_id, permiso) VALUES (115, 1, '');
INSERT INTO Permisos (aplicativo_id, cargo_id, permiso) VALUES (116, 1, '');
INSERT INTO Permisos (aplicativo_id, cargo_id, permiso) VALUES (117, 1, '');
INSERT INTO Permisos (aplicativo_id, cargo_id, permiso) VALUES (118, 1, '');
INSERT INTO Permisos (aplicativo_id, cargo_id, permiso) VALUES (119, 1, '');
INSERT INTO Permisos (aplicativo_id, cargo_id, permiso) VALUES (120, 1, '');
INSERT INTO Permisos (aplicativo_id, cargo_id, permiso) VALUES (121, 1, '');
INSERT INTO Permisos (aplicativo_id, cargo_id, permiso) VALUES (122, 1, '');
INSERT INTO Permisos (aplicativo_id, cargo_id, permiso) VALUES (123, 1, '');
INSERT INTO Permisos (aplicativo_id, cargo_id, permiso) VALUES (124, 1, '');
INSERT INTO Permisos (aplicativo_id, cargo_id, permiso) VALUES (125, 1, '');
INSERT INTO Permisos (aplicativo_id, cargo_id, permiso) VALUES (126, 1, '');
INSERT INTO Permisos (aplicativo_id, cargo_id, permiso) VALUES (127, 1, '');
INSERT INTO Permisos (aplicativo_id, cargo_id, permiso) VALUES (128, 1, '');
INSERT INTO Permisos (aplicativo_id, cargo_id, permiso) VALUES (129, 1, '');
INSERT INTO Permisos (aplicativo_id, cargo_id, permiso) VALUES (130, 1, '');
INSERT INTO Permisos (aplicativo_id, cargo_id, permiso) VALUES (131, 1, '');
INSERT INTO Permisos (aplicativo_id, cargo_id, permiso) VALUES (132, 1, '');
INSERT INTO Permisos (aplicativo_id, cargo_id, permiso) VALUES (133, 1, '');
INSERT INTO Permisos (aplicativo_id, cargo_id, permiso) VALUES (134, 1, '');
INSERT INTO Permisos (aplicativo_id, cargo_id, permiso) VALUES (135, 1, '');
INSERT INTO Permisos (aplicativo_id, cargo_id, permiso) VALUES (136, 1, '');
INSERT INTO Permisos (aplicativo_id, cargo_id, permiso) VALUES (137, 1, '');
INSERT INTO Permisos (aplicativo_id, cargo_id, permiso) VALUES (138, 1, 'X');
INSERT INTO Permisos (aplicativo_id, cargo_id, permiso) VALUES (139, 1, '');
INSERT INTO Permisos (aplicativo_id, cargo_id, permiso) VALUES (140, 1, 'X');
INSERT INTO Permisos (aplicativo_id, cargo_id, permiso) VALUES (141, 1, 'X');
INSERT INTO Permisos (aplicativo_id, cargo_id, permiso) VALUES (142, 1, '');
INSERT INTO Permisos (aplicativo_id, cargo_id, permiso) VALUES (143, 1, '');
INSERT INTO Permisos (aplicativo_id, cargo_id, permiso) VALUES (144, 1, '');
INSERT INTO Permisos (aplicativo_id, cargo_id, permiso) VALUES (145, 1, 'X');
INSERT INTO Permisos (aplicativo_id, cargo_id, permiso) VALUES (146, 1, 'X');






















-- Agrega más permisos según sea necesario